- name: Install Packages Webserver
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: "{{ app_packages }}"
    state: latest

- name: Install Remi Repo
  when: ansible_facts['hostname'] == "webserver" 
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install yum-utils
  when: ansible_facts['hostname'] == "webserver"
  yum: 
    name: yum-utils
    state: latest

- name: Enable remi-php73Repository
  when: ansible_facts['hostname'] == "webserver"
  yum_repository:
    name: remi-php73
    enabled: yes
    description: Extra Packages for Enterprise Linux 7 - $basearch
    mirrorlist: 
Ahmad Ali  5:20 PM
mirrorlist:
http://cdn.remirepo.net/enterprise/7/php73/mirror
- name: Update Repos Webserver
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: "*"
    state: latest
- name: Install PHP 7.3
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: "{{ php_packages }}"
    state: present
    enablerepo: "remi-*,epel,base"
- name: creating soft link
  when: ansible_facts['hostname'] == "webserver"
  file:
    src: /opt/remi/php72/root/usr/bin/php
    dest: /usr/bin/php
    state: link
- name: Download Wordpress
  when: ansible_facts['hostname'] == "webserver"
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
- name: Unarchive a file that is already on the remote machine
  when: ansible_facts['hostname'] == "webserver"
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /tmp/
    remote_src: yes